/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IMdiAppleKeyboardCommand: typeof import('~icons/mdi/apple-keyboard-command')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitPane: typeof import('./src/components/SplitPane/SplitPane.vue')['default']
    SplitPaneDivider: typeof import('./src/components/SplitPane/SplitPaneDivider.vue')['default']
    SplitPanePanel: typeof import('./src/components/SplitPane/SplitPanePanel.vue')['default']
    TabBar: typeof import('./src/components/Tabs/TabBar.vue')['default']
    TabDropOverlay: typeof import('./src/components/Tabs/TabDropOverlay.vue')['default']
    TabGroup: typeof import('./src/components/Tabs/TabGroup.vue')['default']
    TabHeader: typeof import('./src/components/Tabs/TabHeader.vue')['default']
    TabNodeRenderer: typeof import('./src/components/Tabs/TabNodeRenderer.vue')['default']
    Tabs: typeof import('./src/components/Tabs/Tabs.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

// For TSX support
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
  const IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
  const IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
  const IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
  const IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
  const IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
  const IEpSearch: typeof import('~icons/ep/search')['default']
  const IMdiAppleKeyboardCommand: typeof import('~icons/mdi/apple-keyboard-command')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SplitPane: typeof import('./src/components/SplitPane/SplitPane.vue')['default']
  const SplitPaneDivider: typeof import('./src/components/SplitPane/SplitPaneDivider.vue')['default']
  const SplitPanePanel: typeof import('./src/components/SplitPane/SplitPanePanel.vue')['default']
  const TabBar: typeof import('./src/components/Tabs/TabBar.vue')['default']
  const TabDropOverlay: typeof import('./src/components/Tabs/TabDropOverlay.vue')['default']
  const TabGroup: typeof import('./src/components/Tabs/TabGroup.vue')['default']
  const TabHeader: typeof import('./src/components/Tabs/TabHeader.vue')['default']
  const TabNodeRenderer: typeof import('./src/components/Tabs/TabNodeRenderer.vue')['default']
  const Tabs: typeof import('./src/components/Tabs/Tabs.vue')['default']
  const TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
  const WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
}