// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OnDragSignal(arg1) {
  return window['go']['render']['Manager']['OnDragSignal'](arg1);
}

export function OnExternalDragEnter(arg1, arg2) {
  return window['go']['render']['Manager']['OnExternalDragEnter'](arg1, arg2);
}

export function OnExternalDragLeave() {
  return window['go']['render']['Manager']['OnExternalDragLeave']();
}

export function OnLayoutChange(arg1) {
  return window['go']['render']['Manager']['OnLayoutChange'](arg1);
}

export function OnPanelActivate(arg1, arg2) {
  return window['go']['render']['Manager']['OnPanelActivate'](arg1, arg2);
}

export function OnPanelFileDrop(arg1) {
  return window['go']['render']['Manager']['OnPanelFileDrop'](arg1);
}

export function OnPanelResize(arg1, arg2) {
  return window['go']['render']['Manager']['OnPanelResize'](arg1, arg2);
}
