// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {render} from '../models';

export function OnDragSignal(arg1:render.DragSignal):Promise<void>;

export function OnExternalDragEnter(arg1:number,arg2:number):Promise<void>;

export function OnExternalDragLeave():Promise<void>;

export function OnLayoutChange(arg1:Record<string, render.NodeRect>):Promise<void>;

export function OnPanelActivate(arg1:string,arg2:string):Promise<void>;

export function OnPanelResize(arg1:string,arg2:render.NodeRect):Promise<void>;
