// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {folder} from '../models';
import {config} from '../models';
import {connection} from '../models';
import {search} from '../models';

export function CancelSearch(arg1:string):Promise<void>;

export function CancelTransferTask(arg1:string):Promise<void>;

export function ClearFinishedTransferTasks():Promise<void>;

export function CloseConnection(arg1:string):Promise<void>;

export function CreateConnectionDirectory(arg1:string,arg2:string,arg3:string):Promise<folder.FileInfo>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteConnectionEntry(arg1:string,arg2:string):Promise<void>;

export function DownloadConnectionFile(arg1:string,arg2:string):Promise<Array<string>>;

export function DownloadConnectionFileToTemp(arg1:string,arg2:string):Promise<Array<string>>;

export function GetAppConfig():Promise<config.AppConfig>;

export function Greet(arg1:string):Promise<string>;

export function ListConnectionDirectory(arg1:string,arg2:string):Promise<Array<folder.FileInfo>>;

export function ListConnectionStates():Promise<Array<connection.State>>;

export function ListConnections():Promise<Array<connection.Definition>>;

export function ListDrivers():Promise<Array<folder.DriverInfo>>;

export function ListTransferTasks():Promise<Array<folder.TransferTask>>;

export function MoveConnectionEntry(arg1:string,arg2:string,arg3:string):Promise<folder.FileInfo>;

export function OpenConnection(arg1:string):Promise<connection.State>;

export function OpenConnectionFile(arg1:string,arg2:string):Promise<Array<string>>;

export function OpenLocalPath(arg1:string):Promise<void>;

export function PickDownloadDirectory():Promise<string>;

export function PickUploadFile():Promise<string>;

export function RemoveTransferTask(arg1:string):Promise<void>;

export function RenameConnectionEntry(arg1:string,arg2:string,arg3:string):Promise<folder.FileInfo>;

export function RevealLocalPath(arg1:string):Promise<void>;

export function SaveAppConfig(arg1:config.AppConfig):Promise<config.AppConfig>;

export function SaveConnection(arg1:connection.Definition):Promise<connection.Definition>;

export function SaveConnectionFileAs(arg1:string,arg2:string):Promise<Array<string>>;

export function StartSearch(arg1:search.Request):Promise<string>;

export function TestConnection(arg1:connection.Definition):Promise<connection.State>;

export function TransferConnectionEntry(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function UploadConnectionLocalPath(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;
