// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSearch(arg1) {
  return window['go']['main']['App']['CancelSearch'](arg1);
}

export function CancelTransferTask(arg1) {
  return window['go']['main']['App']['CancelTransferTask'](arg1);
}

export function ClearFinishedTransferTasks() {
  return window['go']['main']['App']['ClearFinishedTransferTasks']();
}

export function CloseConnection(arg1) {
  return window['go']['main']['App']['CloseConnection'](arg1);
}

export function CreateConnectionDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateConnectionDirectory'](arg1, arg2, arg3);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteConnectionEntry(arg1, arg2) {
  return window['go']['main']['App']['DeleteConnectionEntry'](arg1, arg2);
}

export function DownloadConnectionFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadConnectionFile'](arg1, arg2);
}

export function DownloadConnectionFileToTemp(arg1, arg2) {
  return window['go']['main']['App']['DownloadConnectionFileToTemp'](arg1, arg2);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListConnectionDirectory(arg1, arg2) {
  return window['go']['main']['App']['ListConnectionDirectory'](arg1, arg2);
}

export function ListConnectionStates() {
  return window['go']['main']['App']['ListConnectionStates']();
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListDrivers() {
  return window['go']['main']['App']['ListDrivers']();
}

export function ListTransferTasks() {
  return window['go']['main']['App']['ListTransferTasks']();
}

export function MoveConnectionEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveConnectionEntry'](arg1, arg2, arg3);
}

export function OpenConnection(arg1) {
  return window['go']['main']['App']['OpenConnection'](arg1);
}

export function OpenConnectionFile(arg1, arg2) {
  return window['go']['main']['App']['OpenConnectionFile'](arg1, arg2);
}

export function OpenLocalPath(arg1) {
  return window['go']['main']['App']['OpenLocalPath'](arg1);
}

export function PickDownloadDirectory() {
  return window['go']['main']['App']['PickDownloadDirectory']();
}

export function PickUploadFile() {
  return window['go']['main']['App']['PickUploadFile']();
}

export function RemoveTransferTask(arg1) {
  return window['go']['main']['App']['RemoveTransferTask'](arg1);
}

export function RenameConnectionEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameConnectionEntry'](arg1, arg2, arg3);
}

export function RevealLocalPath(arg1) {
  return window['go']['main']['App']['RevealLocalPath'](arg1);
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['App']['SaveAppConfig'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveConnectionFileAs(arg1, arg2) {
  return window['go']['main']['App']['SaveConnectionFileAs'](arg1, arg2);
}

export function StartSearch(arg1) {
  return window['go']['main']['App']['StartSearch'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TransferConnectionEntry(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TransferConnectionEntry'](arg1, arg2, arg3, arg4);
}

export function UploadConnectionLocalPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadConnectionLocalPath'](arg1, arg2, arg3);
}
